// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // NOTE: Placeholder web configuration has been added here so the
      // application can initialize on web. Replace the values below with
      // the real credentials from your Firebase Console (Project settings -> Web app).
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHxdW7FSOe79qVm7LdU-Dygx6i6a7lx-k',
    appId: '1:471198039195:android:d9dd06470ae505811a9a3e',
    messagingSenderId: '471198039195',
    projectId: 'inldsevak',
    storageBucket: 'inldsevak.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4I7IpNWNYAAXAz8_h30516G9-nl3kH3A',
    appId: '1:471198039195:ios:da0c90234ec93be51a9a3e',
    messagingSenderId: '471198039195',
    projectId: 'inldsevak',
    storageBucket: 'inldsevak.firebasestorage.app',
    iosBundleId: 'org.amunik.sevak',
  );

  // --- Web FirebaseOptions (REPLACE with real values) ---
  // To get these values go to Firebase Console -> Project Settings -> Your apps (Web)
  // and copy the config values for apiKey, appId (web), authDomain, measurementId (optional).
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:471198039195:web:REPLACE_WITH_ACTUAL_WEB_APP_ID',
    messagingSenderId: '471198039195',
    projectId: 'inldsevak',
    authDomain: 'inldsevak.firebaseapp.com',
    storageBucket: 'inldsevak.firebasestorage.app',
    measurementId: 'G-REPLACE_WITH_MEASUREMENT_ID',
  );

  // --- Windows FirebaseOptions (REPLACE with real values) ---
  // For Windows desktop apps, the FlutterFire CLI would normally populate
  // these values. Add your Windows app credentials here if you have them.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: '1:471198039195:windows:REPLACE_WITH_WINDOWS_APP_ID',
    messagingSenderId: '471198039195',
    projectId: 'inldsevak',
    storageBucket: 'inldsevak.firebasestorage.app',
  );
}
